spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
      fail-fast: false
  profiles:
     active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}


server:
  port: 8888

