sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

# travis encrypt --com SOMEVAR="secure_value" -r "t0rjan/piggymetrics"
env:
  global:
    - secure: "UxiRxjXOLNUi0ywimIrutZ07MtqUu3+T1YszqVW6Gxz6Q4KNf2J6TpHGDvcuLOI/ZbKuldaIeJulfCAT0JovNNA6aW6eBJuUn/6rVqB9Yl+5IhQsaFfywrKUhMRD+AkThIwoFUd0lItOh9jTBT9sGP3BZvfDHIZ2bZ9ip7ickUZTgAKHlCNSPrWFTgJpjZ7EgZFtY7cHNshMiW8P5FY00KSGS+B7Hl652NcWbLNUR48gyTFTLZuG8WkWUfFeZgoPZYJsvW05EJt8Wli/sMyFKC7QpqLgALgPx39UzikcSUJVwJbgvCL229/lmfHODIQwFMJvndQgf0o/cOj1r0CgArPwBmFddX/fNg8GaklRSqgE5fmhVbvArfrWZo0Y0J2n0hwUu53TfdlVBQjI1FUL/tiy+YGusxBRA61iNPHPVBREv9RHEHhqEW9A4aD6+0wmIoEOOueIaBVSY0c6skvZ1YY8npZa8i9dIqgRheSSS8uaBBq5ooU/wYJfF2fpjmcM0BxZOH9pCbOoW2UfydN2/VH7jjY08tJKhPhk8DVZLIMEg2Cc8Vxrw532lO/iDse0/gafEq/Dmswcgxs/kVkoMmQuJYkEKbtK55iOes+aClJID9+Zv/vR+TF1Z0Cl8pi2SDaaFiDJzjiNpiYwD11uXmX21nr10iILLZPZZxyVjlo=" # DOCKER_EMAIL
    - secure: "UxiRxjXOLNUi0ywimIrutZ07MtqUu3+T1YszqVW6Gxz6Q4KNf2J6TpHGDvcuLOI/ZbKuldaIeJulfCAT0JovNNA6aW6eBJuUn/6rVqB9Yl+5IhQsaFfywrKUhMRD+AkThIwoFUd0lItOh9jTBT9sGP3BZvfDHIZ2bZ9ip7ickUZTgAKHlCNSPrWFTgJpjZ7EgZFtY7cHNshMiW8P5FY00KSGS+B7Hl652NcWbLNUR48gyTFTLZuG8WkWUfFeZgoPZYJsvW05EJt8Wli/sMyFKC7QpqLgALgPx39UzikcSUJVwJbgvCL229/lmfHODIQwFMJvndQgf0o/cOj1r0CgArPwBmFddX/fNg8GaklRSqgE5fmhVbvArfrWZo0Y0J2n0hwUu53TfdlVBQjI1FUL/tiy+YGusxBRA61iNPHPVBREv9RHEHhqEW9A4aD6+0wmIoEOOueIaBVSY0c6skvZ1YY8npZa8i9dIqgRheSSS8uaBBq5ooU/wYJfF2fpjmcM0BxZOH9pCbOoW2UfydN2/VH7jjY08tJKhPhk8DVZLIMEg2Cc8Vxrw532lO/iDse0/gafEq/Dmswcgxs/kVkoMmQuJYkEKbtK55iOes+aClJID9+Zv/vR+TF1Z0Cl8pi2SDaaFiDJzjiNpiYwD11uXmX21nr10iILLZPZZxyVjlo=" # DOCKER_USER
    - secure: "VAjaail2uVrsnhWwxTDV4cqjVkw0m7qdqXTmYb0YAuauWYLJ9OVDbugA+lERYCS3YzLhYeVeOB7NCmeB9nYnqZuRNAx+/3tb6cyGNO6lqaH5v5EOtT+PY7Ffc5YgfLsrJMpC6IjWGk8XX7MEkkgxHNtfzbq+NnemCDHgoePIIkg0tvi+DKLDMnsDWiQCTtw1czlxyD163hvxjaFebfimYL2a76m91N0CJFyWtInwH7AAHzBgDmR/My657b9wGt+hOMGTsSSZyyg/GqNMvXNJnx3w6Y5gC87SNfZAsEuE5H83LLZo6p4yU7RNoAfalZ8FX1htdkHUq3lAAcH0Br5OsDFVBHkp3Oi046NdQcPBmO1fh2GtqP0ygTf1DcGXOIjaq4gcGZEqY3P/cbpD5SSddH8138KQUPrHgnRAYuVTJyAmHwzE1Xc6nBIv6zkwC7bZML1R28ahh3y+PpYqm/B/FM9cDC+pidf0RU6h826OyfhEACZc+93EscyvSkGmJBr8JebQdrYhlrRLMKuW6obDmBpeLJlAhosUeHxRxIdbWdPLdnnpsC1/eMB62UVSZvvDs7pN4qHZcWLRD52cdLwolAy04ZKTplmokIMU6c5FMYg9ZgTvVqYOkHgqlU3zQoS2YPER2p6m+rzkGwSxRBqzH5ACxcy5u6vMprqUk/ffgDM=" # DOCKER_PASS
    - secure: "gE8pZ7YdvkWjdS0kgTPQBdT8PZJFsO07Qd4xIKMB48pTITzNS/SSWRU2gSpNkntVGbLe55ooLKJ9nQ+RmSnnprYQdUwEHuJDY/ZN9TyDDHYHbNp/nA5h+KiwYr7dk0w8RtW81y3M9PElU2F7xRAtulbXmmhkyvuOPTcPD3vCT0whRRZausSDrttLEHfZdYoztgfK288wf03oiFDGUWQ3VPu5L3JnYd9L5YnYG5feaU3mqY8nv7HmLKGCH2pzRCVAsVQmsrjCcMwXTpH/eAIvRCIELK2dZwfjnxsfY3JE3sl42VM1EzEk/rsHKLOEx81KLuvVbah4RDfgn0CqzWkXvVYQony18j2eIzOqPWJaDm3MOfD5uBT9+2zbA18aLQgaypnVUEOJoqPL/pED7T8yvPlOwGEfecD5SGwaxYqbUTIG/9O8wd7tb36DVwqBx41drUx3xuIfU/Z+cerpdthuJadqwKbGgl32ml91yQuRBWN/L6vPGnestwJGRuGQRpOJN8n6xidelTTIrgn8ASu/vnLR6Xr0nfWRf8XdbmOuNFjoE1B7FrjkXcv8OfFmW+664w/RiBve5GhXlO0oNnMj5SmyNz0H4JXKjoMzQcdlXB9V6/o04ZnH1IkUOsU1aNBY+M38kRCbMoVMVQRMrTdzBQIBzXzIOBrJKKx2NLkS9ho=" # DOCKER_URL
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_URL

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=t0rjan/piggymetrics-config
  - docker build -t $CONFIG:$COMMIT ./config
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # REGISTRY
  - export REGISTRY=t0rjan/piggymetrics-registry
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  # GATEWAY
  - export GATEWAY=t0rjan/piggymetrics-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # AUTH SERVICE
  - export AUTH_SERVICE=t0rjan/piggymetrics-auth-service
  - docker build -t $AUTH_SERVICE:$COMMIT ./auth-service
  - docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
  - docker push $AUTH_SERVICE

  # ACCOUNT SERVICE
  - export ACCOUNT_SERVICE=t0rjan/piggymetrics-account-service
  - docker build -t $ACCOUNT_SERVICE:$COMMIT ./account-service
  - docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
  - docker push $ACCOUNT_SERVICE

  # STATISTICS SERVICE
  - export STATISTICS_SERVICE=t0rjan/piggymetrics-statistics-service
  - docker build -t $STATISTICS_SERVICE:$COMMIT ./statistics-service
  - docker tag $STATISTICS_SERVICE:$COMMIT $STATISTICS_SERVICE:$TAG
  - docker push $STATISTICS_SERVICE

  # NOTIFICATION_SERVICE
  - export NOTIFICATION_SERVICE=t0rjan/piggymetrics-notification-service
  - docker build -t $NOTIFICATION_SERVICE:$COMMIT ./notification-service
  - docker tag $NOTIFICATION_SERVICE:$COMMIT $NOTIFICATION_SERVICE:$TAG
  - docker push $NOTIFICATION_SERVICE

  # MONITORING
  - export MONITORING=t0rjan/piggymetrics-monitoring
  - docker build -t $MONITORING:$COMMIT ./monitoring
  - docker tag $MONITORING:$COMMIT $MONITORING:$TAG
  - docker push $MONITORING

  # TURBINE STREAM SERVICE
  - export TURBINE=t0rjan/piggymetrics-turbine-stream-service
  - docker build -t $TURBINE:$COMMIT ./turbine-stream-service
  - docker tag $TURBINE:$COMMIT $TURBINE:$TAG
  - docker push $TURBINE

  # MONGO DB
  - export MONGO_DB=t0rjan/piggymetrics-mongodb
  - docker build -t $MONGO_DB:$COMMIT ./mongodb
  - docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
  - docker push $MONGO_DB
