sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

# travis encrypt --com DOCKER_EMAIL="secure_value" -r "t0rjan/piggymetrics"
# travis encrypt --com DOCKER_USER="secure_value" -r "t0rjan/piggymetrics"
# travis encrypt --com DOCKER_PASS="secure_value" -r "t0rjan/piggymetrics"
# travis encrypt --com DOCKER_URL="secure_value" -r "t0rjan/piggymetrics"
env:
  global:
    - secure: "I2nvWANcxZ0EMBKaiMqFxxtVJQ6TEpGY03YXHoVPvTHwwXVOe9PcHfqRY7nOfLDTnZ5gMEAsEAMEkHVYPV7yiO5EWUKA/vmHh/VkkPt8W4zQ2gtPoULa4SSVsvWsqYD4MAb8yteE6fHDCV92y8bRIQnub35QJLrKD+FQhfIpJyzUauYvlFJyWYBFpJz8TcCSlNAcVYeqKRrys5C1SZDVv0FbL6uyooF56QpiDKkVeWeFwtaM13pIlo/Etn09qKbTv1nhhxgHOzkCWrGukQPjYA8x0ZfOfQ0LB8oom6V8a73ZGRtW/3i/87f9jqBXevncCQwVtJcGNiz1h4JkMyHnDUdEtDx4D3X2NZnow3kHpJ3C94Er1tLb6Lnn59mgFztlUyC/IDevBem3zaj3aHHUyEjT3Y/A05ksj00FfJF9oec6+2eGKPiClQg4w0IRQ3rVWjsrmK0ja3Zip9QCPOswaWijS7GuVNxHAn1rE5Ee/9Ok2j4cepqQytHL0Qi2cDIAUTSq+MKf4+6peXUJ2F90h0Gjbr2r31IEisif7hMsX4P90iLcb7YAq4LG5Yf6m8IhVjmP1/ExjzQZQdNBzavAOsqyCgsf64EaBL3kGzNUJxMcRXCHOHwXjZQfpiKPFcsPzy2bshvg0P8zc0cF9536lWHAiX5YGn0xsthtJzAF92o=" # DOCKER_EMAIL
    - secure: "CzsnMaOaSDXWHNdNQKJ8iVFjZss1xJkicfZGXsE3SFS8BrgV9e8byAKHbSYoWvUq0kf1EQuoBt/JwfIREBtTLn++JeyiSa1XbvzRepRrHwdb+PjsGjEpgOK+NC9tE5Jvol5qGyrMjBu2sOUAW/rU7peZc8AOvS1eAcJw/QgVlVZGmnnv9yf0I0+5JdqoEViqpYsgmwdIm4LtKXdc2g6uvmtBUv0CFZoEWkJjTDnLJbA15WUBIKJkxfmvIYXDdPwxFRj6kNi83zv735pKgbM+8NP4OhOFU3N/tuxY4z/jcZHCNm9lpp8br4gFw5owXwttqtaQSAXPztu+tyYG4goh1R2hX04jdRr7o4Do/oSJH/tvUwU4zVBKEgWPzLr0PxLWtDCHr//u1T9Z0v4VDYfbW0K9OTuBgxYAhgVZx55Rx7NEqIEoJ7PAJgzqUKC066z4+978iF6IUcHXIi6v2s7SNkLnCc39v4JbKbqeWzLuW7dsKGyoRwABMTDOEqaoGzpzLyVhy870VupaPOB3t3dlggo6ek4g5aAMisYnSizAGWtESWK1sLU5Eg0u8+fQmDyPnhd5W2SOBK4j5jMb8GiEn/1Aq9Kt3PCs9oYb6KcBjuao/ou4bQyYJ9DNkTzWBIxrjRZr8nFxFpprUS4k4yuhhiL8+SlJP5kRaeJ3lSHHaPE=" # DOCKER_USER
    - secure: "ZAkWSS6hGtrjpYhbp2WS0L55djCVQ38jvaMowoRdMLG/qmuGic3ZcpGqY/1AtM3KESQt+Y84zVrytUjUpUcZWZEv/XwoUijDdgvV2Ez7V3pCWjAjhV0SO1vqRHeqgZY/WXHDgsukNm9ap5+NtfCW+WjPlc3QmOKDBGokYWcmiKtm1vS4cuR2d6fePHCLNvE7Mr3O4jVsP5EIZVF+7q2S1tQOoW38ZxpxCKMX7cFD7dkm3Zv9115Fx6VEtpCNxTD+2RLBdvZy7/k341ZoaKwTpmCi3AK2TV6KLUDLw6F1HJ3Hq0OM74TAP12huVIA6Fj899Fk1U5QZNhd8DZU9ElTVQYhr0thXMa2rfHg0bnIohV6m1luNE7igwispagh/6dfZJuMR62GxqEz8O5BvUwZDuQ1i2Qs8rAXaoO89ZpWDUYrxawjlYbl18Ny1aNrRSh6EhnvglfpBaQDkzLEXR2TYmZ6cs0IUjI55SWD4s/8nwVaSGJD1YFlH8Ra5At0uBulAdPx7MqyNBuhvf/NEHHYwyG8JOWxS6AINVs14tpUZgpY1weUfHeg3OAZ0yyhz3v0BQEU5is/54yd2x+uSU+vrGApU9bzBA24Y5F8t7xXkevCi5kGDNENB4OPduX0L753l7l9IeKBZ7ZOAa2vqpAznh2ip4FMZfd1vf8RZWwVZs8=" # DOCKER_PASS
    - secure: "Ts77L5zv8iUDZSgEGVYdJg5/JMcM9FQHyLgIa3uxKAgD0gUZSZ9YZAwgXUS9r/RQpdb/hK9hIQhVBToJtckdhLPRm6a2YNsdUNFon9+T4vKolwrzsl4RZ+3qhZCH6xOkT05chk9zgJVYsLp97M+7mc2nwiIl02DM12U4BOyjLM7pRdAdkPeE6JvA6b71Pb51fSBzrTcTPs7E1/4YLMpIvhf60kK9p8xytasv97M1f8TqaUjmq1fs7+YrdiOWtc+fsK7tVrPs8touhPbY5p10itLBv8zoOyg33Pj6Jg/7hbx9JQHBhEooA9D2GwRVI3TAglquN9/2of0fbobRAVARRyO0sySd+FQHtWPGArwrkifDN71cMjtE4zHbTSIzByfgfComG/ImFJGdgvNfoAkBZSeEqvesXekApoCabkRoqlPOBgnGRFCpSFMq6/kIfALWZ7ksdhic8/bCK5EsyC+0/9CgjxR8PUx5HL1pYbwYHvlpJHu3Bmv+fpduoxDt98ziAE3Bv2TLZ6hViDBDCvVWAkgzQD2GBHvGChzhL7iqf8hHTP/BjlCZpPmKRtQNyNulGi13/j0OGiLZ9ZoLbUuSoVUaxCG/IrlOoPgbqi1cT8wWqEQXYxbX6YI4I7sK6tu7VBCJDN2KCqa+JWEg6stYE40O28eORpmBNQTD4Tp5TME=" # DOCKER_URL
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login --username $DOCKER_USER --password $DOCKER_PASS $DOCKER_URL

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=$DOCKER_URL/t0rjan/piggymetrics-config
  - docker build -t $CONFIG:$COMMIT ./config
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # REGISTRY
  - export REGISTRY=$DOCKER_URL/t0rjan/piggymetrics-registry
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  # GATEWAY
  - export GATEWAY=$DOCKER_URL/t0rjan/piggymetrics-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # AUTH SERVICE
  - export AUTH_SERVICE=$DOCKER_URL/t0rjan/piggymetrics-auth-service
  - docker build -t $AUTH_SERVICE:$COMMIT ./auth-service
  - docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
  - docker push $AUTH_SERVICE

  # ACCOUNT SERVICE
  - export ACCOUNT_SERVICE=$DOCKER_URL/t0rjan/piggymetrics-account-service
  - docker build -t $ACCOUNT_SERVICE:$COMMIT ./account-service
  - docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
  - docker push $ACCOUNT_SERVICE

  # STATISTICS SERVICE
  - export STATISTICS_SERVICE=$DOCKER_URL/t0rjan/piggymetrics-statistics-service
  - docker build -t $STATISTICS_SERVICE:$COMMIT ./statistics-service
  - docker tag $STATISTICS_SERVICE:$COMMIT $STATISTICS_SERVICE:$TAG
  - docker push $STATISTICS_SERVICE

  # NOTIFICATION_SERVICE
  - export NOTIFICATION_SERVICE=$DOCKER_URL/t0rjan/piggymetrics-notification-service
  - docker build -t $NOTIFICATION_SERVICE:$COMMIT ./notification-service
  - docker tag $NOTIFICATION_SERVICE:$COMMIT $NOTIFICATION_SERVICE:$TAG
  - docker push $NOTIFICATION_SERVICE

  # MONITORING
  - export MONITORING=$DOCKER_URL/t0rjan/piggymetrics-monitoring
  - docker build -t $MONITORING:$COMMIT ./monitoring
  - docker tag $MONITORING:$COMMIT $MONITORING:$TAG
  - docker push $MONITORING

  # TURBINE STREAM SERVICE
  - export TURBINE=$DOCKER_URL/t0rjan/piggymetrics-turbine-stream-service
  - docker build -t $TURBINE:$COMMIT ./turbine-stream-service
  - docker tag $TURBINE:$COMMIT $TURBINE:$TAG
  - docker push $TURBINE

  # MONGO DB
  - export MONGO_DB=$DOCKER_URL/t0rjan/piggymetrics-mongodb
  - docker build -t $MONGO_DB:$COMMIT ./mongodb
  - docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
  - docker push $MONGO_DB
