sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

# travis encrypt --com SOMEVAR="secure_value" -r "t0rjan/piggymetrics"
env:
  global:
    - secure: "HjLwtyACgpaeH92MVD/o3wBfBfcbmUIX/SPHPGpwHyLGlwK4L3wCInVrDfjyZk1W3ehP4HtLyqbeambV5THEozuRI68LKpu180TUGtoZZTARn/9E87KlH38+aJKhVCNb3eBKg7OBkjVsQFnyyWyRfNjKYSHlNtGdWMt+8y5JfNDKdXPfyyLZEl6ZPJrIhODajKgnU+o4A9rNLMUYD8zN+1NtPhvrtuhlXrDFqfQdlNA15mEiOxZS+hXPTz11d+7IkYbIGSya2CiS15XvOGW7qSN6VYpHBLB5XJktc8nvsjdF5ilUhTO+NxP5vAsB1W4VDoUw9JwAue4UL7UFqkhWihgrNLPtCCmHaBeLqzdh2ZbOVzFYr/akmJe5lUQgWFf6L1I+5+iEUCVNMkg6Kfligqii79gr/H1J8gYKZ8FYxS/SPh/qBzzb5821oHRzbk0iOUWoLPoDB5kFXes/xXv27pollt6M4AlGZBhFp2cRV10u7FHxs3qsP+AIyqJdNDQ59lJg087MKFnIXGlnWkcaXtKaGHlOwidanoAb5c/Gs6HhWKTzSf6QD/wPLNjM3Rw7VshKaIAyMiQ8J4G+5VKO5g1PbHbAFx6Z5OTR81jpStVYpwlePb8/o2v5HKcMRkUbZlMkbwWe6vofm6ef0BAF+T/HCHd1aAIw4eFo+FOa2Io=" # DOCKER_EMAIL
    - secure: "hLxAgiDqMh4zO/ZNnHbjS/Qg91g7pm0hA9aXi4zfnsBysuLN21G31JcnA78acybb837LBQ5ji6cqNjono6tcx8EIwKz1Sx7O0hbMU1BecP3bI15unAENQirDcszSYTZdRmpvSpr4DEdt6aQB5lK/vm93egAiTBs5+axi/N+Rj9gAfeDmDWTyIYJJtuPaGX9L4eZs/3Rxfn56WSg7/jmxC0AcSH85M5kj1ksTNZmsNMnqWou9IFMGvE7x8dkMkc3puR/wcU88u1Iakgzgq9ALMfXHQv2wSvQZFaS9e0Oba7S4nEGHcEsF95nJAseQ9VYIKcaoDYcOHWDgY057hfzLDJO/YRZ2Vu643MR/d2BMF3I77Am5Um891I1nb3hzw0emQJOJ3++jVv1w4dQq5WXgOvVm89C7llmJyxWWFQEuLMkYHAxTdjxVuAbHH6olHwUmWj4eG9DGKlT5eh8rL9BZV2esCteHRUX81uA8PL22eYiyT2bbqnrpAEQrPVbHstUHHyzvSdhkRm78xSeCxqdQdfTFRiQrHcqlr0ijtNoHB0yE9OGch/uEWvcLG8eekkgrATCM/oaGbpmDYpj5eVXPAurOkkPnBSVMkAXkn/wmIOaSLU60WsRUu3WbbGex4fI24LBIuLC4jUIwBlUqmppIFkNxPNMV/UXjRpK767Ls7UM=" # DOCKER_USER
    - secure: "CJWJMHVxTm8BN19419ivNS34rdb+u+2k1y9fbn2eVhgeVutdpH6hnEABn6zt1VlHHwJjKUlky5Ni7T2OE+jUU/D2Dh0eh36LVA7baDBCvOiYk6k1zpLIu+y9ovWlzzOot1ukFhjWFT+9lbxO5Ndie80dAWdFTPtCNQIUOk2FDQgW0v2ulNGRS1OqRFOo4DM9jikzfk768xE06D9wDA73zKExBrRz5JQ2udS8uxdyAvD7u/sX1CDEGHf4P8eNQsX81dW/AYPVqCI0+5svEARmgVlKe+kYFkwqbP5ReQ8aU/ssJbs2E+IvOO0exbqRRtgubXa31QaQY3AnjExRnL1BSDa8MVZPRD35FlgIQsNT0ccomlkcptgGjWH51qEUxAQ9Fu7v2N9lcg8SVc1ZwlkZ8tDvonEQbHJRe5ikuExNVWt8WEmv5nL4xZqpTwPmLIpL8/CcfCl1CKtDkA4Wnz4PRRRY6HvqhIBcqrkgEam3zrnGeSLtaKhjAYu3f9CwtteRVrDYEnQVzKNfjraUhAOaAjBrC1uk98NVcHqf/mRMNoHZnIwzMRQLLN9v6q38hgFVDq7MQ4qrPwk5p420IPVK094fagw56qp+venTgyGFGaDRgNq47u8a0qDH2mfkIBrfDlY0lqb59WaeWamFmilO2Fbb8M79ZEShrGhhHMfv3MA=" # DOCKER_PASS
    - secure: "oSRrKjY/oQnF9rPAgScWtJQKVY6SLXnWRoO6v3RIZUvdDlIxGnIXBNxDcuVSQ7+FPj8XA1NhadSGoeXzXYLtjzxCxkVKJvXHESNT98mOke0R/P2/YHiecjmq2lM4g/iH1eY0TuqMWMAOc1q8ZSX04I/7csCo9+m4mtfS58loyfiHU6yAl/wFPMkBT1pTusRD/q7+SqfZGSsZZkYcTJbHa7hpIqZgg3XJlzTqVI4S5/zKia1ug8p/SkwnFwXOIcSzt9xVJFcQcEtg4TE8HrQlSq5iaqXUewn8LMoBvnW0Htt/0rCnetuW1s55p7HoGCWZ8Inr6Jd5b1THduyzza67EiEiujDixnfd8rCcA246ldEHMbjtSUTwZK9U1z9S3qzh2XkWUq3428Uz+Y+cJZmPe/mgEGGNToGcgHzd5kKuIKv1GNMS35/GMCgpWB0EqSsK6MeW07ORVxSQbJWzT4csNaiFHsT7sp2p0p3QYSXJ10hT4K6TMEHJyByWJahA7aTMqplhfHTdfOvD3TEL9A05JV44wG2sGwXupSdvUTLFzX/XI0Ea5GT5k7R7SkN/yLZb4rI9iLCMl6desS0kZDtMVy225VhiBpeZHufThpfiVqLgmcHVpZAhYuBkGgNoE9qFc5BXLfGscg6T9Kq9+YR9khD0I2sIwpVQ5Y5OzBNX3Xw=" # DOCKER_URL
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_URL

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=t0rjan/piggymetrics-config
  - docker build -t $CONFIG:$COMMIT ./config
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # REGISTRY
  - export REGISTRY=t0rjan/piggymetrics-registry
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  # GATEWAY
  - export GATEWAY=t0rjan/piggymetrics-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # AUTH SERVICE
  - export AUTH_SERVICE=t0rjan/piggymetrics-auth-service
  - docker build -t $AUTH_SERVICE:$COMMIT ./auth-service
  - docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
  - docker push $AUTH_SERVICE

  # ACCOUNT SERVICE
  - export ACCOUNT_SERVICE=t0rjan/piggymetrics-account-service
  - docker build -t $ACCOUNT_SERVICE:$COMMIT ./account-service
  - docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
  - docker push $ACCOUNT_SERVICE

  # STATISTICS SERVICE
  - export STATISTICS_SERVICE=t0rjan/piggymetrics-statistics-service
  - docker build -t $STATISTICS_SERVICE:$COMMIT ./statistics-service
  - docker tag $STATISTICS_SERVICE:$COMMIT $STATISTICS_SERVICE:$TAG
  - docker push $STATISTICS_SERVICE

  # NOTIFICATION_SERVICE
  - export NOTIFICATION_SERVICE=t0rjan/piggymetrics-notification-service
  - docker build -t $NOTIFICATION_SERVICE:$COMMIT ./notification-service
  - docker tag $NOTIFICATION_SERVICE:$COMMIT $NOTIFICATION_SERVICE:$TAG
  - docker push $NOTIFICATION_SERVICE

  # MONITORING
  - export MONITORING=t0rjan/piggymetrics-monitoring
  - docker build -t $MONITORING:$COMMIT ./monitoring
  - docker tag $MONITORING:$COMMIT $MONITORING:$TAG
  - docker push $MONITORING

  # TURBINE STREAM SERVICE
  - export TURBINE=t0rjan/piggymetrics-turbine-stream-service
  - docker build -t $TURBINE:$COMMIT ./turbine-stream-service
  - docker tag $TURBINE:$COMMIT $TURBINE:$TAG
  - docker push $TURBINE

  # MONGO DB
  - export MONGO_DB=t0rjan/piggymetrics-mongodb
  - docker build -t $MONGO_DB:$COMMIT ./mongodb
  - docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
  - docker push $MONGO_DB
