version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888
    volumes:
      - ./config/target:/app

  registry:
    build: registry
    volumes:
      - ./registry/target:/app

  gateway:
    build: gateway
    volumes:
      - ./gateway/target:/app

  auth-service:
    build: auth-service
    ports:
      - 5000:5000
    volumes:
      - ./auth-service/target:/app

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  account-service:
    build: account-service
    ports:
      - 6000:6000
    volumes:
      - ./account-service/target:/app

  account-mongodb:
    build: mongodb
    ports:
      - 26000:27017

  statistics-service:
    build: statistics-service
    ports:
      - 7000:7000
    volumes:
      - ./statistics-service/target:/app

  statistics-mongodb:
    build: mongodb
    ports:
      - 27000:27017

  notification-service:
    build: notification-service
    ports:
      - 8000:8000
    volumes:
      - ./notification-service/target:/app

  notification-mongodb:
    build: mongodb
    ports:
      - 28000:27017

  monitoring:
    build: monitoring
    volumes:
      - ./monitoring/target:/app


  turbine-stream-service:
    build: turbine-stream-service
    volumes:
      - ./turbine-stream-service/target:/app
